ARG BASE_IMAGE=not-given
ARG COMPILER_FAMILY=not-given

# Install Python3 (with the trickery for virtual environment).
FROM ${BASE_IMAGE} AS requirements-python

ARG PYTHON_VERSION
ENV VIRTUAL_ENV=/opt/venv-${PYTHON_VERSION}
ENV PATH=${VIRTUAL_ENV}/bin:${PATH}

RUN --mount=target=/requirements/requirements.python.txt,type=bind,source=requirements/requirements.python.txt <<EOF
    set -ex
    apt update
    apt --yes --no-install-recommends install python3 python3-pip python3-venv git
    python3 -m venv $VIRTUAL_ENV

    printf "import re, sys\nif re.match(r'Python ${PYTHON_VERSION}.[0-9]+', '$(python3 --version)') is None: raise RuntimeError(f'Your Python version {sys.version} does not match ${PYTHON_VERSION}.')" | python3

    python3 -m pip install -r /requirements/requirements.python.txt

    apt-helpers clean
EOF

FROM requirements-python AS requirements-compiler-gnu-base

ARG COMPILER_VERSION

RUN <<EOF
    set -ex

    apt-helpers install-packages --clean --update --packages gcc-${COMPILER_VERSION} g++-${COMPILER_VERSION}

    update-alternatives-helpers --prefix /usr/bin \
        --display --level=10 \
        --for-each-of \
            gcc=gcc-${COMPILER_VERSION} \
            g++=g++-${COMPILER_VERSION} \
            $(uname -m)-linux-gnu-gcc=$(uname -m)-linux-gnu-gcc-${COMPILER_VERSION} \
            $(uname -m)-linux-gnu-g++=$(uname -m)-linux-gnu-g++-${COMPILER_VERSION}

    gcc -dumpfullversion -dumpversion
    g++ -dumpfullversion -dumpversion
EOF

FROM requirements-compiler-gnu-base AS requirements-compiler-gnu

FROM requirements-python AS requirements-compiler-rocm

ENV PATH=/opt/rocm/bin:${PATH}

FROM requirements-python AS requirements-compiler-clang

ARG COMPILER_VERSION

RUN <<EOF
    set -ex

    apt-helpers install-packages --update --packages wget lsb-release gpg software-properties-common

    wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | tee /etc/apt/trusted.gpg.d/llvm.asc
    echo "deb https://apt.llvm.org/noble/ llvm-toolchain-noble-${COMPILER_VERSION} main" > /etc/apt/sources.list.d/llvm.list

    apt-helpers install-packages --clean    \
        --update --packages                 \
        clang-${COMPILER_VERSION}           \
        libclang-rt-${COMPILER_VERSION}-dev \
        clang-tidy-${COMPILER_VERSION}      \
        clang-format-${COMPILER_VERSION}    \
        libomp-${COMPILER_VERSION}-dev

    update-alternatives-helpers --prefix /usr/bin --level 10 \
        --display --for-each-of                              \
        clang=clang-${COMPILER_VERSION}                      \
        clang++=clang++-${COMPILER_VERSION}                  \
        clang-tidy=clang-tidy-${COMPILER_VERSION}            \
        clang-format=clang-format-${COMPILER_VERSION}
EOF

FROM requirements-compiler-${COMPILER_FAMILY} AS requirements-system

RUN --mount=target=/requirements/requirements.system.txt,type=bind,source=requirements/requirements.system.txt <<EOF
    set -ex

    apt-helpers install-packages --clean --update \
        --requirement /requirements/requirements.system.txt
EOF

FROM requirements-system AS requirements-cmake

ARG TARGETARCH
ARG CMAKE_VERSION

RUN <<EOF
    set -ex

    if [ "${TARGETARCH}" = "amd64" ];then
        SUFFIX=x86_64
    elif [ "${TARGETARCH}" = "arm64" ];then
        SUFFIX=aarch64
    else
        echo "unsupported target arch ${TARGETARCH}"
    fi

    INSTALLER=cmake-${CMAKE_VERSION}-linux-${SUFFIX}.sh

    wget https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/${INSTALLER}

    mkdir -p /opt/cmake-${CMAKE_VERSION}

    sh ${INSTALLER} --skip-license --prefix=/opt/cmake-${CMAKE_VERSION}/

    rm ${INSTALLER}
EOF

ARG CMAKE_PACKAGE_MANAGER_VERSION

ADD https://github.com/cpm-cmake/CPM.cmake/releases/download/v${CMAKE_PACKAGE_MANAGER_VERSION}/CPM.cmake \
    /opt/cpm-${CMAKE_PACKAGE_MANAGER_VERSION}/

ENV PATH=/opt/cmake-${CMAKE_VERSION}/bin:${PATH}

# Compile Doxygen.
FROM requirements-cmake AS doxygen-compile

ARG DOXYGEN_VERSION

ADD https://github.com/doxygen/doxygen/archive/refs/tags/Release_${DOXYGEN_VERSION//./_}.tar.gz /tmp/

RUN <<EOF
    set -ex

    cd /tmp

    tar -xvf Release_$(echo ${DOXYGEN_VERSION} | tr . _).tar.gz

    apt-helpers install-packages --clean --update --packages flex bison

    cd doxygen-Release_$(echo ${DOXYGEN_VERSION} | tr . _)

    cmake -S . -B build -DCMAKE_INSTALL_PREFIX=/opt/doxygen-${DOXYGEN_VERSION}

    cmake --build build -j4 --target install
EOF

# Compile Google Test.
FROM requirements-cmake AS google-test-compile

ARG GOOGLETEST_VERSION

ADD https://github.com/google/googletest/archive/refs/tags/v${GOOGLETEST_VERSION}.tar.gz /tmp/

RUN <<EOF
    set -ex

    cd /tmp

    tar -xzf v${GOOGLETEST_VERSION}.tar.gz

    cd googletest-${GOOGLETEST_VERSION}

    cmake -S . -B build \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/opt/google-test-${GOOGLETEST_VERSION}

    cmake --build build -j4

    cmake --build build --target install
EOF

FROM requirements-cmake AS requirements-backend

REPLACE_REQUIREMENTS_BACKEND

# Build Kokkos.
FROM requirements-backend AS kokkos-compile

ARG COMPILER_FAMILY
ARG KOKKOS_ARCHS
ARG KOKKOS_PRESET
ARG KOKKOS_SHA
ARG KOKKOS_USERNAME

ADD https://github.com/${KOKKOS_USERNAME}/kokkos/archive/${KOKKOS_SHA}.tar.gz /tmp/

RUN --mount=target=/cmake/presets/kokkos.json,type=bind,source=cmake/presets/kokkos.json <<EOF
    set -ex

    cd /tmp

    tar -xzf ${KOKKOS_SHA}.tar.gz

    cd kokkos-${KOKKOS_SHA}

    cp /cmake/presets/kokkos.json CMakePresets.json

    cmake -S . --preset=${KOKKOS_PRESET} \
        $([ -n "$KOKKOS_ARCHS" ] && echo $KOKKOS_ARCHS | tr ',' '\n' | sed 's/^/-DKokkos_ARCH_/; s/$/=ON/') \
        -DCMAKE_INSTALL_PREFIX=/opt/kokkos-${KOKKOS_SHA}/${KOKKOS_PRESET}

    cmake --build --preset=${KOKKOS_PRESET} -j4 --target install
EOF

FROM kokkos-compile AS kokkos-utils-compile

ARG COMPILER_FAMILY
ARG KOKKOS_PRESET
ARG KOKKOS_SHA
ARG KOKKOS_UTILS_SHA

ADD https://github.com/uliegecsm/kokkos-utils/archive/${KOKKOS_UTILS_SHA}.tar.gz /tmp/

RUN --mount=target=/cmake/presets/kokkos-utils.json,type=bind,source=cmake/presets/kokkos-utils.json <<EOF
    set -ex

    cd /tmp

    tar -xzf ${KOKKOS_UTILS_SHA}.tar.gz

    cd kokkos-utils-${KOKKOS_UTILS_SHA}

    cp /cmake/presets/kokkos-utils.json CMakePresets.json

    export Kokkos_ROOT=/opt/kokkos-${KOKKOS_SHA}/${KOKKOS_PRESET}

    cmake -S . --preset=${KOKKOS_PRESET} \
        -DCMAKE_INSTALL_PREFIX=/opt/kokkos-utils-${KOKKOS_UTILS_SHA}/${KOKKOS_PRESET}

    cmake --build --preset=${KOKKOS_PRESET} -j4 --target=install
EOF

# Build the final image from previous stages.
FROM requirements-backend AS final

ARG DOXYGEN_VERSION
ARG GOOGLETEST_VERSION
ARG KOKKOS_PRESET
ARG KOKKOS_SHA
ARG KOKKOS_UTILS_SHA

COPY --from=doxygen-compile      /opt/doxygen-${DOXYGEN_VERSION}                        /opt/doxygen-${DOXYGEN_VERSION}
COPY --from=google-test-compile  /opt/google-test-${GOOGLETEST_VERSION}                 /opt/google-test-${GOOGLETEST_VERSION}
COPY --from=kokkos-compile       /opt/kokkos-${KOKKOS_SHA}/${KOKKOS_PRESET}             /opt/kokkos-${KOKKOS_SHA}/${KOKKOS_PRESET}
COPY --from=kokkos-utils-compile /opt/kokkos-utils-${KOKKOS_UTILS_SHA}/${KOKKOS_PRESET} /opt/kokkos-utils-${KOKKOS_UTILS_SHA}/${KOKKOS_PRESET}

ENV Doxygen_ROOT=/opt/doxygen-${DOXYGEN_VERSION}
ENV GTest_ROOT=/opt/google-test-${GOOGLETEST_VERSION}
ENV Kokkos_ROOT=/opt/kokkos-${KOKKOS_SHA}/${KOKKOS_PRESET}
ENV KokkosUtils_ROOT=/opt/kokkos-utils-${KOKKOS_UTILS_SHA}/${KOKKOS_PRESET}
