ARG BASE_IMAGE=not-given
ARG COMPILER_FAMILY=not-given

# Install Python3 (with the trickery for virtual environment).
FROM ${BASE_IMAGE} AS requirements-python

ARG PYTHON_VERSION
ENV VIRTUAL_ENV=/opt/venv-${PYTHON_VERSION}
ENV PATH=${VIRTUAL_ENV}/bin:${PATH}

RUN <<EOF
    set -ex
    apt update
    apt --yes --no-install-recommends install python3 python3-pip python3-venv git
    python3 -m venv $VIRTUAL_ENV

    printf "import re, sys\nif re.match(r'Python ${PYTHON_VERSION}.[0-9]+', '$(python3 --version)') is None: raise RuntimeError(f'Your Python version {sys.version} does not match ${PYTHON_VERSION}.')" | python3

    python3 -m pip install system-helpers

    apt-helpers clean
EOF

FROM requirements-python AS requirements-system

RUN --mount=target=/requirements/requirements.system.txt,type=bind,source=requirements/requirements.system.txt <<EOF
    set -ex

    apt-helpers install-packages --clean --update \
        --requirement /requirements/requirements.system.txt
EOF

FROM requirements-system AS requirements-cmake

ARG TARGETARCH
ARG CMAKE_VERSION

RUN <<EOF
    set -ex

    if [ "${TARGETARCH}" = "amd64" ];then
        SUFFIX=x86_64
    elif [ "${TARGETARCH}" = "arm64" ];then
        SUFFIX=aarch64
    else
        echo "unsupported target arch ${TARGETARCH}"
    fi

    INSTALLER=cmake-${CMAKE_VERSION}-linux-${SUFFIX}.sh

    wget https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/${INSTALLER}

    mkdir -p /opt/cmake-${CMAKE_VERSION}

    sh ${INSTALLER} --skip-license --prefix=/opt/cmake-${CMAKE_VERSION}/

    rm ${INSTALLER}
EOF

ARG CMAKE_PACKAGE_MANAGER_VERSION

ADD https://github.com/cpm-cmake/CPM.cmake/releases/download/v${CMAKE_PACKAGE_MANAGER_VERSION}/CPM.cmake \
    /opt/cpm-${CMAKE_PACKAGE_MANAGER_VERSION}/

ENV PATH=/opt/cmake-${CMAKE_VERSION}/bin:${PATH}

FROM requirements-cmake AS requirements-compiler-gnu

ARG COMPILER_VERSION

RUN <<EOF
    set -ex

    apt-helpers install-packages --clean --update --packages gcc-${COMPILER_VERSION} g++-${COMPILER_VERSION}

    update-alternatives-helpers --prefix /usr/bin \
        --display --level=10 \
        --for-each-of \
            gcc=gcc-${COMPILER_VERSION} \
            g++=g++-${COMPILER_VERSION} \
            $(uname -m)-linux-gnu-gcc=$(uname -m)-linux-gnu-gcc-${COMPILER_VERSION} \
            $(uname -m)-linux-gnu-g++=$(uname -m)-linux-gnu-g++-${COMPILER_VERSION}

    gcc -dumpfullversion -dumpversion
    g++ -dumpfullversion -dumpversion
EOF

COPY <<EOF /opt/toolchain.cmake
set(CMAKE_C_COMPILER /usr/bin/gcc)
set(CMAKE_CXX_COMPILER /usr/bin/g++)
EOF

FROM requirements-cmake AS requirements-compiler-rocm

ENV PATH=/opt/rocm/bin:${PATH}
ENV LD_LIBRARY_PATH=/opt/rocm/lib:$LD_LIBRARY_PATH

COPY <<EOF /opt/toolchain.cmake
set(CMAKE_C_COMPILER /usr/bin/amdclang)
set(CMAKE_CXX_COMPILER /usr/bin/amdclang++)
EOF

FROM requirements-cmake AS requirements-compiler-clang

ARG COMPILER_VERSION

RUN <<EOF
    set -ex

    apt-helpers install-packages --update --packages wget lsb-release gpg software-properties-common

    UBUNTU_CODENAME=$(grep -oP '(?<=^VERSION_CODENAME=).+' /etc/os-release)
    LLVM_KEY=/etc/apt/keyrings/llvm.asc
    wget -qO "${LLVM_KEY}" https://apt.llvm.org/llvm-snapshot.gpg.key
    echo "deb [signed-by=${LLVM_KEY}] https://apt.llvm.org/${UBUNTU_CODENAME}/ llvm-toolchain-${UBUNTU_CODENAME}-${COMPILER_VERSION} main" > /etc/apt/sources.list.d/llvm.list

    apt-helpers install-packages --clean    \
        --update --packages                 \
        clang-${COMPILER_VERSION}           \
        libclang-rt-${COMPILER_VERSION}-dev \
        clang-tidy-${COMPILER_VERSION}      \
        clang-format-${COMPILER_VERSION}    \
        libomp-${COMPILER_VERSION}-dev

    update-alternatives-helpers --prefix /usr/bin --level 10 \
        --display --for-each-of                              \
        clang=clang-${COMPILER_VERSION}                      \
        clang++=clang++-${COMPILER_VERSION}                  \
        clang-tidy=clang-tidy-${COMPILER_VERSION}            \
        clang-format=clang-format-${COMPILER_VERSION}
EOF

COPY <<EOF /opt/toolchain.cmake
set(CMAKE_C_COMPILER /usr/bin/clang)
set(CMAKE_CXX_COMPILER /usr/bin/clang++)
EOF

FROM requirements-cmake AS requirements-compiler-intel

ARG COMPILER_VERSION

RUN <<EOF
    set -ex

    apt-helpers install-packages --update --packages gpg wget

    wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB \
        | gpg --dearmor | tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
    echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" \
        | tee /etc/apt/sources.list.d/oneAPI.list

    apt-helpers install-packages --update --packages intel-oneapi-compiler-dpcpp-cpp-${COMPILER_VERSION}
EOF

ENV PATH=/opt/intel/oneapi/compiler/latest/bin/:$PATH
ENV LD_LIBRARY_PATH=/opt/intel/oneapi/compiler/latest/lib:/opt/intel/oneapi/umf/latest/lib:$LD_LIBRARY_PATH

ARG UNIFIED_RUNTIME_VERSION=7.0.0

RUN --mount=type=tmpfs,target=/tmp/build <<EOF
    set -ex

    apt-helpers install-packages --clean --packages libhwloc-dev hwloc

    cd /tmp/build

    wget https://github.com/intel/llvm/archive/refs/tags/v${UNIFIED_RUNTIME_VERSION}.tar.gz

    tar -xf v${UNIFIED_RUNTIME_VERSION}.tar.gz

    cd llvm-${UNIFIED_RUNTIME_VERSION}/unified-runtime

    cmake -S . -B build \
      -DCMAKE_C_COMPILER=gcc \
      -DCMAKE_CXX_COMPILER=g++ \
      -DUR_BUILD_TESTS=OFF \
      -DUR_ENABLE_TRACING=ON \
      -DUR_BUILD_ADAPTER_CUDA=ON \
      -DUR_BUILD_ADAPTER_OPENCL=OFF \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=/opt/ur-${UNIFIED_RUNTIME_VERSION}

    cmake --build build -j4 --target=install
EOF

ENV UR_ADAPTERS_SEARCH_PATH=/opt/ur-${UNIFIED_RUNTIME_VERSION}/lib

COPY <<EOF /opt/toolchain.cmake
set(CMAKE_C_COMPILER icx)
set(CMAKE_CXX_COMPILER icpx)
EOF

# Compile Doxygen.
FROM requirements-compiler-${COMPILER_FAMILY} AS doxygen-compile

ARG DOXYGEN_VERSION

ADD https://github.com/doxygen/doxygen/archive/refs/tags/Release_${DOXYGEN_VERSION//./_}.tar.gz /tmp/

RUN <<EOF
    set -ex

    cd /tmp

    tar -xvf Release_$(echo ${DOXYGEN_VERSION} | tr . _).tar.gz

    apt-helpers install-packages --clean --update --packages flex bison

    cd doxygen-Release_$(echo ${DOXYGEN_VERSION} | tr . _)

    cmake -S . -B build \
        --toolchain /opt/toolchain.cmake \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/opt/doxygen-${DOXYGEN_VERSION}

    cmake --build build -j4 --target install
EOF

# Compile Google Test.
FROM requirements-compiler-${COMPILER_FAMILY} AS google-test-compile

ARG GOOGLETEST_VERSION

ADD https://github.com/google/googletest/archive/refs/tags/v${GOOGLETEST_VERSION}.tar.gz /tmp/

RUN <<EOF
    set -ex

    cd /tmp

    tar -xzf v${GOOGLETEST_VERSION}.tar.gz

    cd googletest-${GOOGLETEST_VERSION}

    cmake -S . -B build \
        --toolchain /opt/toolchain.cmake \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/opt/google-test-${GOOGLETEST_VERSION}

    cmake --build build -j4

    cmake --build build --target install
EOF

FROM requirements-compiler-${COMPILER_FAMILY} AS requirements-backend

REPLACE_REQUIREMENTS_BACKEND

# Build Kokkos.
FROM requirements-backend AS kokkos-compile

ARG CMAKE_BUILD_TYPE
ARG COMPILER_FAMILY
ARG KOKKOS_ARCHS
ARG KOKKOS_PRESET
ARG KOKKOS_SHA
ARG KOKKOS_USERNAME

ADD https://github.com/${KOKKOS_USERNAME}/kokkos/archive/${KOKKOS_SHA}.tar.gz /tmp/

RUN --mount=target=/cmake/presets/kokkos.json,type=bind,source=cmake/presets/kokkos.json \
    --mount=target=/patches,type=bind,source=docker/patches <<EOF
    set -ex

    cd /tmp

    tar -xzf ${KOKKOS_SHA}.tar.gz

    cd kokkos-${KOKKOS_SHA}
    patch -p1 -i /patches/kokkos-hpx-finalize-9443.patch

    cp /cmake/presets/kokkos.json CMakePresets.json

    : "${CMAKE_BUILD_TYPE?is not defined.}"

    cmake -S . --preset=${KOKKOS_PRESET} -LA \
        -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} \
        $([ -n "$KOKKOS_ARCHS" ] && echo $KOKKOS_ARCHS | tr ',' '\n' | sed 's/^/-DKokkos_ARCH_/; s/$/=ON/') \
        -DCMAKE_INSTALL_PREFIX=/opt/kokkos-${KOKKOS_SHA}/${KOKKOS_PRESET}

    cmake --build --preset=${KOKKOS_PRESET} -j4 --target install
EOF

FROM kokkos-compile AS kokkos-utils-compile

ARG CMAKE_BUILD_TYPE
ARG COMPILER_FAMILY
ARG KOKKOS_PRESET
ARG KOKKOS_SHA
ARG KOKKOS_UTILS_SHA

ADD https://github.com/uliegecsm/kokkos-utils/archive/${KOKKOS_UTILS_SHA}.tar.gz /tmp/

RUN --mount=target=/cmake/presets/kokkos-utils.json,type=bind,source=cmake/presets/kokkos-utils.json <<EOF
    set -ex

    cd /tmp

    tar -xzf ${KOKKOS_UTILS_SHA}.tar.gz

    cd kokkos-utils-${KOKKOS_UTILS_SHA}

    cp /cmake/presets/kokkos-utils.json CMakePresets.json

    export Kokkos_ROOT=/opt/kokkos-${KOKKOS_SHA}/${KOKKOS_PRESET}

    : "${CMAKE_BUILD_TYPE?is not defined.}"

    cmake -S . --preset=${KOKKOS_PRESET} \
        -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} \
        -DCMAKE_INSTALL_PREFIX=/opt/kokkos-utils-${KOKKOS_UTILS_SHA}/${KOKKOS_PRESET}

    cmake --build --preset=${KOKKOS_PRESET} -j4 --target=install
EOF

# Build the final image from previous stages.
FROM requirements-backend AS final

ARG DOXYGEN_VERSION
ARG GOOGLETEST_VERSION
ARG KOKKOS_PRESET
ARG KOKKOS_SHA
ARG KOKKOS_UTILS_SHA

COPY --from=doxygen-compile      /opt/doxygen-${DOXYGEN_VERSION}                        /opt/doxygen-${DOXYGEN_VERSION}
COPY --from=google-test-compile  /opt/google-test-${GOOGLETEST_VERSION}                 /opt/google-test-${GOOGLETEST_VERSION}
COPY --from=kokkos-compile       /opt/kokkos-${KOKKOS_SHA}/${KOKKOS_PRESET}             /opt/kokkos-${KOKKOS_SHA}/${KOKKOS_PRESET}
COPY --from=kokkos-utils-compile /opt/kokkos-utils-${KOKKOS_UTILS_SHA}/${KOKKOS_PRESET} /opt/kokkos-utils-${KOKKOS_UTILS_SHA}/${KOKKOS_PRESET}

ENV Doxygen_ROOT=/opt/doxygen-${DOXYGEN_VERSION}
ENV GTest_ROOT=/opt/google-test-${GOOGLETEST_VERSION}
ENV Kokkos_ROOT=/opt/kokkos-${KOKKOS_SHA}/${KOKKOS_PRESET}
ENV KokkosUtils_ROOT=/opt/kokkos-utils-${KOKKOS_UTILS_SHA}/${KOKKOS_PRESET}
