# This file contains setup w.r.t. mapping from enabled Kokkos devices to execution space type.
include_guard(GLOBAL)

set(KOKKOS_DEVICE_TO_EXECUTION_SPACE_CUDA "Cuda")
set(KOKKOS_DEVICE_TO_EXECUTION_SPACE_HIP "HIP")
set(KOKKOS_DEVICE_TO_EXECUTION_SPACE_HPX "Experimental::HPX")
set(KOKKOS_DEVICE_TO_EXECUTION_SPACE_OPENMP "OpenMP")
set(KOKKOS_DEVICE_TO_EXECUTION_SPACE_SERIAL "Serial")
set(KOKKOS_DEVICE_TO_EXECUTION_SPACE_SYCL "SYCL")
set(KOKKOS_DEVICE_TO_EXECUTION_SPACE_THREADS "Threads")
