string(JSON DOXYGEN_VERSION GET "${DEPENDENCIES_JSON}" "github" "doxygen")

find_package(Doxygen ${DOXYGEN_VERSION} REQUIRED)

# Fetch tag files of other projects.
fetch_doxygen_tag(kokkos-utils https://uliegecsm.github.io/kokkos-utils)

set(HOMEPAGE_MD ${CMAKE_SOURCE_DIR}/README.md)

set(DOXYGEN_CITE_BIB_FILES ${CMAKE_CURRENT_SOURCE_DIR}/references.bib)
set(DOXYGEN_ENABLE_PREPROCESSING YES)
set(DOXYGEN_EXTRACT_ALL YES)
set(DOXYGEN_FILE_PATTERNS *.c *.cpp *.h *.hpp)
set(DOXYGEN_IMAGE_PATH ${CMAKE_SOURCE_DIR})
set(DOXYGEN_MACRO_EXPANSION YES)
set(DOXYGEN_PREDEFINED __DOXYGEN__)
set(DOXYGEN_REFERENCES_RELATION YES)
set(DOXYGEN_SOURCE_BROWSER YES)
set(DOXYGEN_TIMESTAMP YES)
set(DOXYGEN_USE_MDFILE_AS_MAINPAGE ${HOMEPAGE_MD})
set(DOXYGEN_WARN_AS_ERROR YES)
set(DOXYGEN_WARN_IF_UNDOCUMENTED NO)

get_target_property(GTest_gtest_INTERFACE_INCLUDE_DIRECTORIES GTest::gtest INTERFACE_INCLUDE_DIRECTORIES)
get_target_property(Kokkos_kokkoscore_INTERFACE_INCLUDE_DIRECTORIES Kokkos::kokkoscore INTERFACE_INCLUDE_DIRECTORIES)
set(DOXYGEN_INCLUDE_PATH ${Kokkos_kokkoscore_INTERFACE_INCLUDE_DIRECTORIES}
                         ${GTest_gtest_INTERFACE_INCLUDE_DIRECTORIES} ${CMAKE_SOURCE_DIR}
)

doxygen_add_docs(docs ${HOMEPAGE_MD} ${CMAKE_SOURCE_DIR}/kokkos-execution ${CMAKE_SOURCE_DIR}/tests)
