name: Build Docker images

description: Build Docker images used by the CI.

on:
  workflow_dispatch:
    inputs:
      force-rebuild:
        description: 'Force re-build of all Docker images.'
        required: false
        type: boolean
        default: false
  workflow_call:
    outputs:
      CI_IMAGE:
        value: ${{ jobs.set-vars.outputs.CI_IMAGE }}

permissions:
  contents: read
  packages: write
  pull-requests: read

jobs:
  set-vars:
    uses: ./.github/workflows/set-vars.yml
    secrets: inherit

  setup-skips:
    runs-on: ubuntu-slim
    outputs:
      build-builder: ${{ steps.build-builder.outputs.build-builder }}
      build-images: ${{ steps.build-images.outputs.build-images }}
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v6

      - id: build-builder-changed-files
        uses: tj-actions/changed-files@v47
        with:
          files: |
            .github/workflows/build.images.yml
            docker/dockerfile.builder

      - id: build-builder
        env:
          ANY_CHANGED: ${{ steps.build-builder-changed-files.outputs.any_changed == 'true' }}
          FORCE: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs['force-rebuild'] }}
        run: |
          if [ "$ANY_CHANGED" = "true" ] || [ "$FORCE" = "true" ]; then
              BUILD_BUILDER=true
          else
              BUILD_BUILDER=false
          fi
          echo "BUILD_BUILDER set to ${BUILD_BUILDER} because:"
          echo "    - any changed: ${ANY_CHANGED}"
          echo "    - force      : ${FORCE}"
          echo "build-builder=${BUILD_BUILDER}" >> $GITHUB_OUTPUT

      - id: build-images-changed-files
        uses: tj-actions/changed-files@v47
        with:
          files: |
            .github/workflows/build.images.yml
            dependencies.json
            docker/dockerfile

      - id: build-images
        env:
          ANY_CHANGED: ${{ steps.build-images-changed-files.outputs.any_changed == 'true' }}
          FORCE: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs['force-rebuild'] }}
        run: |
          if [ "$ANY_CHANGED" = "true" ] || [ "$FORCE" = "true" ]; then
              BUILD_IMAGES=true
          else
              BUILD_IMAGES=false
          fi
          echo "BUILD_IMAGES set to ${BUILD_IMAGES} because:"
          echo "    - any changed: ${ANY_CHANGED}"
          echo "    - force      : ${FORCE}"
          echo "build-images=${BUILD_IMAGES}" >> $GITHUB_OUTPUT

  build-builder:
    needs: [set-vars, setup-skips]
    if: ${{ ! failure() && ! cancelled() && needs.setup-skips.outputs.build-builder == 'true' }}
    runs-on: [self-hosted, linux, docker, amd64]
    container:
      image: docker:latest
    steps:
      - uses: actions/checkout@v6

      - uses: docker/login-action@v4
        with:
          registry: ${{ needs.set-vars.outputs.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v4

      - uses: docker/build-push-action@v7.0.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/main' }}
          file: docker/dockerfile.builder
          tags: ${{ needs.set-vars.outputs.CI_BUILDER }}
          cache-from: type=registry,ref=${{ needs.set-vars.outputs.CI_BUILDER }}
          cache-to: type=inline
          labels: "org.opencontainers.image.source=${{ github.repositoryUrl }}"

  build-images:
    needs: [set-vars, setup-skips, build-builder]
    if: ${{ ! failure() && ! cancelled() && needs.setup-skips.outputs.build-images == 'true' }}
    runs-on: ${{ fromJSON(matrix.runs-on || '["self-hosted", "linux", "docker", "amd64"]') }}
    container:
      image: ${{ needs.set-vars.outputs.CI_BUILDER }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - compiler:
              family: gnu
              version: 14
            base_image: ubuntu:24.04
            platforms: linux/amd64
          - kokkos_backends: [Threads]
            compiler:
              family: gnu
              version: 14
            base_image: ubuntu:24.04
            platforms: linux/amd64
          - kokkos_backends: [OpenMP]
            compiler:
              family: gnu
              version: 14
            base_image     : ubuntu:24.04
            platforms      : linux/amd64
          - kokkos_backends: [OpenMP]
            compiler:
              family: clang
              version: 22
            base_image     : ubuntu:24.04
            platforms      : linux/amd64
          - kokkos_backends: [HPX]
            compiler:
              family: gnu
              version: 14
            base_image     : ubuntu:24.04
            platforms      : linux/amd64
          - kokkos_backends: [HPX]
            compiler:
              family: clang
              version: 22
            base_image     : ubuntu:24.04
            platforms      : linux/amd64
          - kokkos_backends: [OpenMP, Cuda]
            compiler:
              family: clang
              version: 21
            base_image     : nvcr.io/nvidia/cuda:12.8.1-devel-ubuntu24.04
            platforms      : linux/amd64
            kokkos_archs   : [VOLTA70]
          - kokkos_backends: [OpenMP, Cuda]
            compiler:
              family: clang
              version: 22
            base_image     : nvcr.io/nvidia/cuda:13.1.0-devel-ubuntu24.04
            platforms      : linux/amd64
            kokkos_archs   : [BLACKWELL120]
          - kokkos_backends: [HPX, Cuda]
            compiler:
              family: clang
              version: 22
            base_image     : nvcr.io/nvidia/cuda:13.1.0-devel-ubuntu24.04
            platforms      : linux/amd64
            kokkos_archs   : [BLACKWELL120]
          - kokkos_backends: [OpenMP, HIP]
            compiler:
              family: rocm
              version: 7.0.2
            base_image     : rocm/dev-ubuntu-24.04:7.0.2
            platforms      : linux/amd64
            kokkos_archs   : [ZEN5, AMD_GFX1201]
          - kokkos_backends: [OpenMP, SYCL]
            compiler:
              family: intel
              version: 2025.3
            base_image: nvcr.io/nvidia/cuda:12.8.1-devel-ubuntu24.04
            platforms: linux/amd64
            kokkos_archs: [VOLTA70]
          # After this line come the images we build, but don't test.
          - kokkos_backends: [OpenMP]
            compiler:
              family: clang
              version: 22
            base_image     : ubuntu:24.04
            platforms      : linux/arm64
            runs-on        : "['self-hosted', 'linux', 'docker', 'arm64']"
          - kokkos_backends: [HPX, Cuda]
            compiler:
              family: clang
              version: 22
            base_image     : nvcr.io/nvidia/cuda:13.1.0-devel-ubuntu24.04
            platforms      : linux/amd64
            kokkos_archs   : [ZEN3, AMPERE86]
    steps:
      - uses: actions/checkout@v6

      - shell: sh
        run  : |
          echo CMAKE_VERSION=$(jq '.cmake' dependencies.json -j) >> $GITHUB_ENV
          echo CMAKE_PACKAGE_MANAGER_VERSION=$(jq '.github.cpm' dependencies.json -j) >> $GITHUB_ENV
          echo DOXYGEN_VERSION=$(jq '.github.doxygen' dependencies.json -j) >> $GITHUB_ENV
          echo GOOGLETEST_VERSION=$(jq '.github.googletest' dependencies.json -j) >> $GITHUB_ENV
          echo KOKKOS_SHA=$(jq '.github.kokkos.sha' dependencies.json -j) >> $GITHUB_ENV
          echo KOKKOS_USERNAME=$(jq '.github.kokkos.username' dependencies.json -j) >> $GITHUB_ENV
          echo KOKKOS_UTILS_SHA=$(jq '.github."kokkos-utils".sha' dependencies.json -j) >> $GITHUB_ENV
          echo PYTHON_VERSION=$(jq '.python' dependencies.json -j) >> $GITHUB_ENV

      - run: |
          python3 docker/backend.py \
            --kokkos-backends=${{ join(matrix.kokkos_backends, ',') }} \
            --dependencies=dependencies.json \
            --input=docker/dockerfile \
            --compiler-family=${{ matrix.compiler.family }} \
            --output=docker/dockerfile.backend

      - uses: docker/login-action@v4
        with:
          registry: ${{ needs.set-vars.outputs.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id : compute-tag-suffix
        run: |
          # We don't use multi-platform build for ARM64 because it's too slow. Instead, we use a native
          # runner and append '-arm64' to the image tag.
          TAG_SUFFIX=${{ matrix.kokkos_archs && '-' || '' }}${{ join(matrix.kokkos_archs, '-')}}${{ runner.arch == 'ARM64' && '-arm64' || '' }}
          TAG_SUFFIX=$(echo ${TAG_SUFFIX} | tr '[:upper:]' '[:lower:]')
          echo "Computed image tag suffix: ${TAG_SUFFIX}."
          echo "TAG_SUFFIX=${TAG_SUFFIX}" >> $GITHUB_OUTPUT

      - id : compute-tag
        run: |
          TAG=${{ needs.set-vars.outputs.CI_IMAGE }}:${{ matrix.compiler.family }}-${{ matrix.compiler.version }}${{ matrix.kokkos_backends && format('-{0}', join(matrix.kokkos_backends, '-')) || '' }}${{ steps.compute-tag-suffix.outputs.TAG_SUFFIX }}
          echo "TAG=${TAG}" >> $GITHUB_OUTPUT

      - uses: docker/setup-buildx-action@v4

      - uses: docker/build-push-action@v7.0.0
        with:
            context: .
            platforms: ${{ matrix.platforms }}
            push: ${{ github.ref == 'refs/heads/main' }}
            file: docker/dockerfile.backend
            tags: ${{ steps.compute-tag.outputs.tag }}
            cache-from: type=registry,ref=${{ steps.compute-tag.outputs.tag }}
            cache-to: type=inline
            build-args: |
                BASE_IMAGE=${{ matrix.base_image }}
                CMAKE_VERSION=${{ env.CMAKE_VERSION }}
                CMAKE_PACKAGE_MANAGER_VERSION=${{ env.CMAKE_PACKAGE_MANAGER_VERSION }}
                COMPILER_FAMILY=${{ matrix.compiler.family }}
                COMPILER_VERSION=${{ matrix.compiler.version }}
                DOXYGEN_VERSION=${{ env.DOXYGEN_VERSION }}
                GOOGLETEST_VERSION=${{ env.GOOGLETEST_VERSION }}
                KOKKOS_ARCHS=${{ matrix.kokkos_archs && join(matrix.kokkos_archs, ',') || '' }}
                KOKKOS_PRESET=${{ matrix.compiler.family }}${{ matrix.kokkos_backends && format('-{0}', join(matrix.kokkos_backends, '-')) || '' }}
                KOKKOS_SHA=${{ env.KOKKOS_SHA }}
                KOKKOS_USERNAME=${{ env.KOKKOS_USERNAME }}
                KOKKOS_UTILS_SHA=${{ env.KOKKOS_UTILS_SHA }}
                PYTHON_VERSION=${{ env.PYTHON_VERSION }}
            labels: "org.opencontainers.image.source=${{ github.repositoryUrl }}"
