on:
  workflow_call:
    inputs:
      CI_IMAGE:
        required: true
        type: string

permissions:
  contents: read
  packages: read

jobs:
  clang:
    runs-on: [self-hosted, linux, docker, amd64]
    container:
      image: ${{ inputs.CI_IMAGE }}:clang-22-OpenMP
    steps:
      - uses: actions/checkout@v6
      - run: git ls-files *.hpp *.h *.cpp *.c | xargs clang-format-22 --dry-run --Werror

  cmake:
    runs-on: [self-hosted, linux, docker, amd64]
    container:
      image: ${{ inputs.CI_IMAGE }}:clang-22-OpenMP
    steps:
      - uses: actions/checkout@v6
      - run: |
          cmake-format --config-files=.cmake-format.py \
            --log-level=debug \
            --check \
            $(git ls-files CMakeLists.txt '*.cmake')
