name: Run tests

description: Build and test.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # At 06:00 on Sunday.
    - cron:  '0 6 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read
  packages: read

env:
  REGISTRY: ghcr.io

jobs:
  build-images:
    uses: ./.github/workflows/build.images.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
      pull-requests: read

  clang-format:
    needs: [build-images]
    uses: ./.github/workflows/clang.format.yml
    with:
      CI_IMAGE: ${{ needs.build-images.outputs.CI_IMAGE }}

  build-and-test:
    needs: [build-images, clang-format]
    runs-on: ${{ fromJSON(matrix.runs-on || '["self-hosted", "linux", "docker", "amd64"]') }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - backend        : OpenMP
            compiler_family: gcc
          - backend        : OpenMP
            compiler_family: clang
    container:
      image: ${{ needs.build-images.outputs.CI_IMAGE }}:${{ matrix.compiler_family }}-${{ matrix.backend }}
    steps:
      - uses: actions/checkout@v6
      - run: |
          cmake -S . -B build-${{ matrix.compiler_family }}-${{ matrix.backend }}
      - run: |
          cmake --build build-${{ matrix.compiler_family }}-${{ matrix.backend }} -j4
